[package]
name = "mevrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { version = "0.17.0", features = ["abigen"] }
futures = "0.3.24"
tokio = { version = "1.21.1", features = ["full"] }
